
name: Asciidoctor Build Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Convert AsciiDoctor Docker Action
      uses: Analog-inc/asciidoctor-action@v1.2.2
      with:
        shellcommand: "asciidoctor OG_Format.adoc"
