name: Export and publish document

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate HTML document
      uses: Analog-inc/asciidoctor-action@v1.2.2
      with:
        shellcommand: "asciidoctor --verbose -D build -o index.html OG_Format.adoc; cp -r figures build/"
    - name: Generate PDF document
      uses: Analog-inc/asciidoctor-action@v1.2.2
      with:
        shellcommand: "asciidoctor-pdf --verbose -d book OG_Format.adoc -D build"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: 'build'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
